export const SOCIAL_MEDIA_LIST_REQUEST = 'SOCIAL_MEDIA_LIST_REQUEST'
export const SOCIAL_MEDIA_LIST_SUCCESS = 'SOCIAL_MEDIA_LIST_SUCCESS'
export const SOCIAL_MEDIA_LIST_FAIL = 'SOCIAL_MEDIA_LIST_FAIL'
export const SOCIAL_MEDIA_LIST_RESET = 'SOCIAL_MEDIA_LIST_RESET'

export const SOCIAL_MEDIA_CREATE_REQUEST = 'SOCIAL_MEDIA_CREATE_REQUEST'
export const SOCIAL_MEDIA_CREATE_SUCCESS = 'SOCIAL_MEDIA_CREATE_SUCCESS'
export const SOCIAL_MEDIA_CREATE_FAIL = 'SOCIAL_MEDIA_CREATE_FAIL'
export const SOCIAL_MEDIA_CREATE_RESET = 'SOCIAL_MEDIA_CREATE_RESET'

export const SOCIAL_MEDIA_UPDATE_REQUEST = 'SOCIAL_MEDIA_UPDATE_REQUEST'
export const SOCIAL_MEDIA_UPDATE_SUCCESS = 'SOCIAL_MEDIA_UPDATE_SUCCESS'
export const SOCIAL_MEDIA_UPDATE_FAIL = 'SOCIAL_MEDIA_UPDATE_FAIL'
export const SOCIAL_MEDIA_UPDATE_RESET = 'SOCIAL_MEDIA_UPDATE_RESET'

export const SOCIAL_MEDIA_DETAIL_REQUEST = 'SOCIAL_MEDIA_DETAIL_REQUEST'
export const SOCIAL_MEDIA_DETAIL_SUCCESS = 'SOCIAL_MEDIA_DETAIL_SUCCESS'
export const SOCIAL_MEDIA_DETAIL_FAIL = 'SOCIAL_MEDIA_DETAIL_FAIL'
export const SOCIAL_MEDIA_DETAIL_RESET = 'SOCIAL_MEDIA_DETAIL_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'