export const SOCIAL_MEDIA_LIST_REQUEST = 'SOCIAL_MEDIA_LIST_REQUEST'
export const SOCIAL_MEDIA_LIST_SUCCESS = 'SOCIAL_MEDIA_LIST_SUCCESS'
export const SOCIAL_MEDIA_LIST_FAIL = 'SOCIAL_MEDIA_LIST_FAIL'
export const SOCIAL_MEDIA_LIST_RESET = 'SOCIAL_MEDIA_LIST_RESET'