version: "3.9"

services:
  database:
    image: postgres
    container_name: database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123456
      - POSTGRES_DB=db_store_flow
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend_store_flow
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/user/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
