openapi: 3.0.0
info:
  title: Docs API app store-flow
  description: Documentation to API store flow.
  version: 0.1.0
servers:
  - url: http://localhost:3333
    description: Internal staging server for testing

components:
  securityDefinitions:
    myCookie:          
      type: apiKey
      name: cookie
      in: header

  responses:
    UnauthorizedError:
      description: Token is missing or invalid !

tags:
- name: "session"
  description: "Create User, authentication, reset password, forgot password  and logout"
  
- name: "user"
  description: "List all user, update user and get store from user "

- name: "store"
  description: "create, update, list all, list by seller"
  
paths:
  /login:
    post:
      tags:
      - "session"
      summary: "Logs user into the system"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "user_dms"
        in: "body"
        description: "The user_dms for login"
        required: true
        type: "string"
      - name: "password"
        in: "body"
        description: "The password for login"
        required: true
        type: "string"
      responses:
        "200":
          success: true        
        "400":
          description: "Email or password incorrect !"

  /store/new:
    post:
      tags: 
      - "store"
      summary: "Create a category"
      security: 
       - myCookie: []
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "store"
        schema:
          type: "object"
          properties: 
            cnpj: 
              type: "string"
            
            name: 
              type: "string"
              
            brand: 
              type: "string"
              
      responses:
        "201":
          success: true
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    
