export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST'
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS'
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL'

export const STORE_DETAIL_REQUEST = 'STORE_DETAIL_REQUEST'
export const STORE_DETAIL_SUCCESS = 'STORE_DETAIL_SUCCESS'
export const STORE_DETAIL_FAIL = 'STORE_DETAIL_FAIL'
export const STORE_DETAIL_RESET = 'STORE_DETAIL_RESET'


export const STORE_CREATE_REQUEST = 'STORE_CREATE_REQUEST'
export const STORE_CREATE_SUCCESS = 'STORE_CREATE_SUCCESS'
export const STORE_CREATE_FAIL = 'STORE_CREATE_FAIL'
export const STORE_CREATE_RESET = 'STORE_CREATE_RESET'

export const STORE_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST'
export const STORE_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS'
export const STORE_UPDATE_FAIL = 'STORE_UPDATE_FAIL'
export const STORE_UPDATE_RESET = 'STORE_UPDATE_RESET'

export const STORE_LIST_SELLERS_REQUEST = 'STORE_LIST_SELLERS_REQUEST'
export const STORE_LIST_SELLERS_SUCCESS = 'STORE_LIST_SELLERS_SUCCESS'
export const STORE_LIST_SELLERS_FAIL = 'STORE_LIST_SELLERS_FAIL'


export const CLEAN_ERRORS = 'CLEAN_ERRORS'