export const SELLER_LIST_REQUEST = 'SELLER_LIST_REQUEST'
export const SELLER_LIST_SUCCESS = 'SELLER_LIST_SUCCESS'
export const SELLER_LIST_FAIL = 'SELLER_LIST_FAIL'

export const SELLER_DETAIL_REQUEST = 'SELLER_DETAIL_REQUEST'
export const SELLER_DETAIL_SUCCESS = 'SELLER_DETAIL_SUCCESS'
export const SELLER_DETAIL_FAIL = 'SELLER_DETAIL_FAIL'
export const SELLER_DETAIL_RESET = 'SELLER_DETAIL_RESET'

export const SELLER_CREATE_REQUEST = 'SELLER_CREATE_REQUEST'
export const SELLER_CREATE_SUCCESS = 'SELLER_CREATE_SUCCESS'
export const SELLER_CREATE_FAIL = 'SELLER_CREATE_FAIL'
export const SELLER_CREATE_RESET = 'SELLER_CREATE_RESET'

export const SELLER_UPDATE_REQUEST = 'SELLER_UPDATE_REQUEST'
export const SELLER_UPDATE_SUCCESS = 'SELLER_UPDATE_SUCCESS'
export const SELLER_UPDATE_FAIL = 'SELLER_UPDATE_FAIL'
export const SELLER_UPDATE_RESET = 'SELLER_UPDATE_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'