export const STORE_FLOW_LIST_REQUEST = 'STORE_FLOW_LIST_REQUEST'
export const STORE_FLOW_LIST_SUCCESS = 'STORE_FLOW_LIST_SUCCESS'
export const STORE_FLOW_LIST_FAIL = 'STORE_FLOW_LIST_FAIL'

export const STORE_FLOW_CREATE_REQUEST = 'STORE_FLOW_CREATE_REQUEST'
export const STORE_FLOW_CREATE_SUCCESS = 'STORE_FLOW_CREATE_SUCCESS'
export const STORE_FLOW_CREATE_FAIL = 'STORE_FLOW_CREATE_FAIL'
export const STORE_FLOW_CREATE_RESET = 'STORE_FLOW_CREATE_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'