export const SERVICE_TYPE_LIST_REQUEST = 'SERVICE_TYPE_LIST_REQUEST'
export const SERVICE_TYPE_LIST_SUCCESS = 'SERVICE_TYPE_LIST_SUCCESS'
export const SERVICE_TYPE_LIST_FAIL = 'SERVICE_TYPE_LIST_FAIL'

export const SERVICE_TYPE_DETAIL_REQUEST = 'SERVICE_TYPE_DETAIL_REQUEST'
export const SERVICE_TYPE_DETAIL_SUCCESS = 'SERVICE_TYPE_DETAIL_SUCCESS'
export const SERVICE_TYPE_DETAIL_FAIL = 'SERVICE_TYPE_DETAIL_FAIL'

export const SERVICE_TYPE_CREATE_RESET = 'ST_CREATE_RESET'
export const SERVICE_TYPE_CREATE_REQUEST = 'SERVICE_TYPE_CREATE_REQUEST'
export const SERVICE_TYPE_CREATE_SUCCESS = 'SERVICE_TYPE_CREATE_SUCCESS'
export const SERVICE_TYPE_CREATE_FAIL = 'SERVICE_TYPE_CREATE_FAIL'

export const SERVICE_TYPE_UPDATE_REQUEST = 'SERVICE_TYPE_UPDATE_REQUEST'
export const SERVICE_TYPE_UPDATE_SUCCESS = 'SERVICE_TYPE_UPDATE_SUCCESS'
export const SERVICE_TYPE_UPDATE_FAIL = 'SERVICE_TYPE_UPDATE_FAIL'
export const SERVICE_TYPE_UPDATE_RESET = 'SERVICE_TYPE_UPDATE_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'