export const SEGMENT_CREATE_REQUEST = 'SEGMENT_CREATE_REQUEST'
export const SEGMENT_CREATE_SUCCESS = 'SEGMENT_CREATE_SUCCESS'
export const SEGMENT_CREATE_FAIL = 'SEGMENT_CREATE_FAIL'
export const SEGMENT_CREATE_RESET = 'SEGMENT_CREATE_RESET'

export const SEGMENT_LIST_REQUEST = 'SEGMENT_LIST_REQUEST'
export const SEGMENT_LIST_SUCCESS = 'SEGMENT_LIST_SUCCESS'
export const SEGMENT_LIST_FAIL = 'SEGMENT_LIST_FAIL'
export const SEGMENT_LIST_RESET = 'SEGMENT_LIST_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'