export const SEGMENT_CREATE_REQUEST = 'SEGMENT_CREATE_REQUEST'
export const SEGMENT_CREATE_SUCCESS = 'SEGMENT_CREATE_SUCCESS'
export const SEGMENT_CREATE_FAIL = 'SEGMENT_CREATE_FAIL'
export const SEGMENT_CREATE_RESET = 'SEGMENT_CREATE_RESET'

export const SEGMENT_LIST_REQUEST = 'SEGMENT_LIST_REQUEST'
export const SEGMENT_LIST_SUCCESS = 'SEGMENT_LIST_SUCCESS'
export const SEGMENT_LIST_FAIL = 'SEGMENT_LIST_FAIL'
export const SEGMENT_LIST_RESET = 'SEGMENT_LIST_RESET'

export const SEGMENT_DETAIL_REQUEST = 'SEGMENT_DETAIL_REQUEST'
export const SEGMENT_DETAIL_SUCCESS = 'SEGMENT_DETAIL_SUCCESS'
export const SEGMENT_DETAIL_FAIL = 'SEGMENT_DETAIL_FAIL'
export const SEGMENT_DETAIL_RESET = 'SEGMENT_DETAIL_RESET'

export const SEGMENT_UPDATE_REQUEST = 'SEGMENT_UPDATE_REQUEST'
export const SEGMENT_UPDATE_SUCCESS = 'SEGMENT_UPDATE_SUCCESS'
export const SEGMENT_UPDATE_FAIL = 'SEGMENT_UPDATE_FAIL'
export const SEGMENT_UPDATE_RESET = 'SEGMENT_UPDATE_RESET'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'