export const PROSPECTION_LIST_REQUEST = 'PROSPECTION_LIST_REQUEST'
export const PROSPECTION_LIST_SUCCESS = 'PROSPECTION_LIST_SUCCESS'
export const PROSPECTION_LIST_FAIL = 'PROSPECTION_LIST_FAIL'

export const PROSPECTION_DETAIL_REQUEST = 'PROSPECTION_DETAIL_REQUEST'
export const PROSPECTION_DETAIL_SUCCESS = 'PROSPECTION_DETAIL_SUCCESS'
export const PROSPECTION_DETAIL_FAIL = 'PROSPECTION_DETAIL_FAIL'
export const PROSPECTION_DETAIL_RESET = 'PROSPECTION_DETAIL_RESET'

export const PROSPECTION_CREATE_RESET = 'ST_CREATE_RESET'
export const PROSPECTION_CREATE_REQUEST = 'PROSPECTION_CREATE_REQUEST'
export const PROSPECTION_CREATE_SUCCESS = 'PROSPECTION_CREATE_SUCCESS'
export const PROSPECTION_CREATE_FAIL = 'PROSPECTION_CREATE_FAIL'

export const PROSPECTION_UPDATE_REQUEST = 'PROSPECTION_UPDATE_REQUEST'
export const PROSPECTION_UPDATE_SUCCESS = 'PROSPECTION_UPDATE_SUCCESS'
export const PROSPECTION_UPDATE_FAIL = 'PROSPECTION_UPDATE_FAIL'
export const PROSPECTION_UPDATE_RESET = 'PROSPECTION_UPDATE_RESET'

export const PROSPECTION_DELETE_REQUEST = 'PROSPECTION_DELETE_REQUEST'
export const PROSPECTION_DELETE_SUCCESS = 'PROSPECTION_DELETE_SUCCESS'
export const PROSPECTION_DELETE_FAIL = 'PROSPECTION_DELETE_FAIL'

export const PROSPECTION_CLEAN_ERRORS = 'PROSPECTION_CLEAN_ERRORS'

